# Configuration file for the STM32 for VSCode extension
# Arrays can be inputted in two ways. One is: [entry_1, entry_2, ..., entry_final]
# or by adding an indented list below the variable name e.g.:
# VARIABLE:
# - entry_1
# - entry_2

# The project name
target: STM32F746G_DISCO
# Can be C or C++
language: C++

optimization: Og

# MCU settings
targetMCU: stm32f7x
cpu: cortex-m7 # type of cpu e.g. cortex-m4
fpu: fpv5-sp-d16 # Defines how floating points are defined. Can be left empty.
floatAbi: -mfloat-abi=hard
ldscript: STM32F746NGHx_FLASH.ld # linker script

# Compiler definitions. The -D prefix for the compiler will be automatically added.
cDefinitions: 
  - USE_HAL_DRIVER
  - STM32F746xx

cxxDefinitions: 
  - USE_HAL_DRIVER
  - STM32F746xx

asDefinitions: []

# Compiler definition files. you can add a single files or an array of files for different definitions.
# The file is expected to have a definition each new line.
# This allows to include for example a .definition file which can be ignored in git and can contain
# This can be convenient for passing along secrets at compile time, or generating a file for per device setup.
cDefinitionsFile:
cxxDefinitionsFile:
asDefinitionsFile:

# Compiler flags
cFlags: []
cxxFlags: []
assemblyFlags: []
linkerFlags: 
  - -specs=nano.specs
  - -specs=nosys.specs


# libraries to be included. The -l prefix to the library will be automatically added.
libraries: 
  - c
  - m
  - nosys

# Library directories. Folders can be added here that contain custom libraries.
libraryDirectories:


# Files or folders that will be excluded from compilation.
# Glob patterns (https://www.wikiwand.com/en/Glob_(programming)) can be used.
# Do mind that double stars are reserved in yaml
# these should be escaped with a: \ or the name should be in double quotes e.g. "**.test.**"
excludes: 
  - "**/Examples/**"
  - "**/examples/**"
  - "**/Example/**"
  - "**/example/**"
  - "**_template.*"
  - "Middlewares/ST/touchgfx/framework/source/platform/hal/simulator/sdl2/HALSDL2.cpp"
  - "Middlewares/ST/touchgfx/framework/source/platform/hal/simulator/sdl2/HALSDL2_icon.cpp"
  - "Middlewares/ST/touchgfx/framework/source/platform/hal/simulator/sdl2/OSWrappers.cpp"
  - "Middlewares/ST/touchgfx/os/OSWrappers_cmsis.cpp"
  - "Middlewares/ST/touchgfx/os/OSWrappers.cpp"
  - "Middlewares/ST/touchgfx/framework/source/platform/driver/touch/SDL2TouchController.cpp"
  - "Middlewares/ST/touchgfx/framework/source/touchgfx/widgets/**"
  - "Middlewares/ST/touchgfx/framework/source/touchgfx/containers/**"
  - "TouchGFX/generated/simulator/src/mainBase.cpp"
  - "TouchGFX/simulator/main.cpp"

# Include directories (directories containing .h or .hpp files)
# If a CubeMX makefile is present it will automatically include the include directories from that makefile.
includeDirectories: 
  - Core/Inc
  - LIBJPEG/App
  - LIBJPEG/Target
  - TouchGFX/App
  - TouchGFX/target/generated
  - TouchGFX/target
  - TouchGFX/generated/fonts/include
  - TouchGFX/generated/gui_generated/include
  - TouchGFX/generated/images/include
  - TouchGFX/generated/simulator/include
  - TouchGFX/generated/texts/include
  - TouchGFX/generated/videos/include
  - Middlewares/ST/touchgfx/framework/include
  - Middlewares/ST/touchgfx/framework/include/platform/hal/simulator/sdl2/vendor
  - TouchGFX/gui/include
  - Drivers/STM32F7xx_HAL_Driver/Inc
  - Drivers/STM32F7xx_HAL_Driver/Inc/Legacy
  - Middlewares/Third_Party/FreeRTOS/Source/include
  - Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2
  - Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1
  - Middlewares/Third_Party/LibJPEG/include
  - Drivers/CMSIS/Device/ST/STM32F7xx/Include
  - Drivers/CMSIS/Include
  - Drivers/BSP/Components/ft5336
  - Drivers/BSP/STM32746G-Discovery
  - Inc/**
  - Core/Inc/**
  - Core/Lib/**
  - Src/**
  - Core/Src/**
  - Core/Lib/**


# Files that should be included in the compilation.
# If a CubeMX makefile is present it will automatically include the  c and cpp/cxx files from that makefile.
# Glob patterns (https://www.wikiwand.com/en/Glob_(programming)) can be used.
# Do mind that double stars are reserved in yaml
# these should be escaped with a: \ or the name should be in double quotes e.g. "HARDWARE_DRIVER*.c"
sourceFiles:  
  - startup_stm32f746xx.s
  - TouchGFX/App/app_touchgfx.c
  - Core/Src/main.c
  - Core/Src/freertos.c
  - Core/Src/stm32f7xx_it.c
  - Core/Src/stm32f7xx_hal_msp.c
  - Core/Src/stm32f7xx_hal_timebase_tim.c
  - LIBJPEG/App/libjpeg.c
  - Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cortex.c
  - Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_crc.c
  - Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_crc_ex.c
  - Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc.c
  - Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc_ex.c
  - Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash.c
  - Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash_ex.c
  - Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_gpio.c
  - Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma.c
  - Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma_ex.c
  - Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr.c
  - Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr_ex.c
  - Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal.c
  - Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c.c
  - Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c_ex.c
  - Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_exti.c
  - Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma2d.c
  - Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_ll_fmc.c
  - Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sdram.c
  - Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_ltdc.c
  - Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_ltdc_ex.c
  - Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dsi.c
  - Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_qspi.c
  - Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim.c
  - Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim_ex.c
  - Core/Src/system_stm32f7xx.c
  - Middlewares/Third_Party/FreeRTOS/Source/croutine.c
  - Middlewares/Third_Party/FreeRTOS/Source/event_groups.c
  - Middlewares/Third_Party/FreeRTOS/Source/list.c
  - Middlewares/Third_Party/FreeRTOS/Source/queue.c
  - Middlewares/Third_Party/FreeRTOS/Source/stream_buffer.c
  - Middlewares/Third_Party/FreeRTOS/Source/tasks.c
  - Middlewares/Third_Party/FreeRTOS/Source/timers.c
  - Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/cmsis_os2.c
  - Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c
  - Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1/port.c
  - Middlewares/Third_Party/LibJPEG/source/jcapimin.c
  - Middlewares/Third_Party/LibJPEG/source/jcapistd.c
  - Middlewares/Third_Party/LibJPEG/source/jdapimin.c
  - Middlewares/Third_Party/LibJPEG/source/jdapistd.c
  - Middlewares/Third_Party/LibJPEG/source/jcomapi.c
  - Middlewares/Third_Party/LibJPEG/source/jcparam.c
  - Middlewares/Third_Party/LibJPEG/source/jctrans.c
  - Middlewares/Third_Party/LibJPEG/source/jdtrans.c
  - Middlewares/Third_Party/LibJPEG/source/jcinit.c
  - Middlewares/Third_Party/LibJPEG/source/jcmaster.c
  - Middlewares/Third_Party/LibJPEG/source/jcmainct.c
  - Middlewares/Third_Party/LibJPEG/source/jcprepct.c
  - Middlewares/Third_Party/LibJPEG/source/jccoefct.c
  - Middlewares/Third_Party/LibJPEG/source/jccolor.c
  - Middlewares/Third_Party/LibJPEG/source/jcsample.c
  - Middlewares/Third_Party/LibJPEG/source/jcdctmgr.c
  - Middlewares/Third_Party/LibJPEG/source/jfdctint.c
  - Middlewares/Third_Party/LibJPEG/source/jfdctfst.c
  - Middlewares/Third_Party/LibJPEG/source/jfdctflt.c
  - Middlewares/Third_Party/LibJPEG/source/jchuff.c
  - Middlewares/Third_Party/LibJPEG/source/jcarith.c
  - Middlewares/Third_Party/LibJPEG/source/jcmarker.c
  - Middlewares/Third_Party/LibJPEG/source/jdatadst.c
  - Middlewares/Third_Party/LibJPEG/source/jdmaster.c
  - Middlewares/Third_Party/LibJPEG/source/jdinput.c
  - Middlewares/Third_Party/LibJPEG/source/jdmainct.c
  - Middlewares/Third_Party/LibJPEG/source/jdcoefct.c
  - Middlewares/Third_Party/LibJPEG/source/jdpostct.c
  - Middlewares/Third_Party/LibJPEG/source/jdmarker.c
  - Middlewares/Third_Party/LibJPEG/source/jdhuff.c
  - Middlewares/Third_Party/LibJPEG/source/jdarith.c
  - Middlewares/Third_Party/LibJPEG/source/jddctmgr.c
  - Middlewares/Third_Party/LibJPEG/source/jidctint.c
  - Middlewares/Third_Party/LibJPEG/source/jidctfst.c
  - Middlewares/Third_Party/LibJPEG/source/jidctflt.c
  - Middlewares/Third_Party/LibJPEG/source/jdsample.c
  - Middlewares/Third_Party/LibJPEG/source/jdcolor.c
  - Middlewares/Third_Party/LibJPEG/source/jdmerge.c
  - Middlewares/Third_Party/LibJPEG/source/jquant1.c
  - Middlewares/Third_Party/LibJPEG/source/jquant2.c
  - Middlewares/Third_Party/LibJPEG/source/jdatasrc.c
  - Middlewares/Third_Party/LibJPEG/source/jaricom.c
  - Middlewares/Third_Party/LibJPEG/source/jerror.c
  - Middlewares/Third_Party/LibJPEG/source/jmemmgr.c
  - Middlewares/Third_Party/LibJPEG/source/jutils.c
  - Middlewares/Third_Party/LibJPEG/source/jmemnobs.c
  - Src/**
  - Core/Src/**
  - Core/Lib/**



# When no makefile is present it will show a warning pop-up.
# However when compilation without the CubeMX Makefile is desired, this can be turned of.
suppressMakefileWarning: false

# Custom makefile rules
# Here custom makefile rules can be added to the STM32Make.make file
# an example of how this can be used is commented out below.
customMakefileRules:
# - command: sayhello
#   rule: echo "hello"
#   dependsOn: $(BUILD_DIR)/$(TARGET).elf # can be left out    

# Additional flags which will be used when invoking the make command
makeFlags:
# - -O  # use this option when the output of make is mixed up only works for make version 4.0 and upwards
# - --silent # use this option to silence the output of the build
    